version: '3.8'
services:
  supabase:
    image: supabase/postgres:latest
    container_name: supabase
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_USER: youruser
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"   # Postgres
    volumes:
      - ./supabase:/docker-entrypoint-initdb.d

  storage:
    image: minio/minio
    container_name: storage
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - ./storage:/data