name: irondex
description: "피트니스 머신 리뷰 앱"
publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.0
  provider: ^6.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo/
    - assets/icon/
    - assets/auth/
